# Generated by Django 5.2 on 2025-05-07 13:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+40777777777", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
