# Generated by Django 5.2 on 2025-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
