# Generated by Django 5.1.4 on 2025-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dispatcher_phone_num',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
