# Generated by Django 5.1.2 on 2025-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
