# Generated by Django 5.2 on 2025-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='status',
            field=models.CharField(choices=[(0, 'Free'), (1, 'In Use')], default=0),
        ),
        migrations.AddField(
            model_name='trailerdocument',
            name='status',
            field=models.CharField(choices=[(0, 'Free'), (1, 'In Use')], default=0),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[(0, 'Free'), (1, 'In Use')], default=0),
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='status',
            field=models.CharField(choices=[(0, 'Free'), (1, 'In Use')], default=0),
        ),
    ]
