# Generated by Django 5.2 on 2025-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_trailer_status_trailerdocument_status_truck_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='trailerdocument',
            name='status',
            field=models.CharField(default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='truckdocument',
            name='status',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
