# Generated by Django 5.2 on 2025-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_trailer_status_alter_trailerdocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailerdocument',
            name='issuing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='issuing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
