# Generated by Django 5.2 on 2025-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_trailerdocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
