# Generated by Django 5.2 on 2025-06-06 18:43

from django.db import migrations

def populate_reference(apps, schema_editor):
    MyModel = apps.get_model('vehicles', 'Trailer')
    for obj in MyModel.objects.all():
        obj.category = "default_category"
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_trailer_type'),
    ]

    operations = [
        migrations.RunPython(populate_reference)
    ]
