# Generated by Django 5.2 on 2025-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20250606_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=False),
        ),
    ]
