# Generated by Django 5.2 on 2025-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20250606_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
