# Generated by Django 5.1.4 on 2025-03-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_point_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_truck', models.CharField(max_length=100)),
                ('status_truck_text', models.CharField(max_length=255)),
                ('status_goods', models.CharField(max_length=100)),
                ('truck_combination', models.CharField(max_length=100)),
                ('status_coupling', models.CharField(max_length=100)),
                ('trailer_type', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(max_length=100)),
                ('status_trailer_wagon', models.CharField(max_length=100)),
                ('status_loaded_truck', models.CharField(max_length=100)),
                ('detraction', models.CharField(max_length=100)),
                ('status_transport', models.CharField(default='not started', max_length=100)),
                ('documents', models.JSONField(default=list)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_transports', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_transports', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.route')),
            ],
        ),
    ]
