# Generated by Django 5.1.2 on 2025-04-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_trailer_transport_trailer_trailerdocument_truck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expeditor_nume', models.CharField(max_length=255)),
                ('expeditor_adresa', models.CharField(max_length=255)),
                ('expeditor_tara', models.CharField(max_length=100)),
                ('destinatar_nume', models.CharField(max_length=255)),
                ('destinatar_adresa', models.CharField(max_length=255)),
                ('destinatar_tara', models.CharField(max_length=100)),
                ('loc_livrare', models.CharField(max_length=255)),
                ('loc_incarcare', models.CharField(max_length=255)),
                ('data_incarcare', models.DateField()),
                ('marci_numere', models.CharField(max_length=255)),
                ('numar_colete', models.IntegerField()),
                ('mod_ambalare', models.CharField(max_length=255)),
                ('natura_marfii', models.CharField(max_length=255)),
                ('nr_static', models.CharField(max_length=100)),
                ('greutate_bruta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cubaj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructiuni_expeditor', models.TextField(blank=True, null=True)),
                ('conventii_speciale', models.TextField(blank=True, null=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_dispatcher', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_driver', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmrs', to='base.transport')),
            ],
        ),
    ]
