# Generated by Django 5.1.3 on 2025-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='goods_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='delay_estimation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='status_trailer_wagon_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='goods_photos',
            field=models.ManyToManyField(blank=True, to='base.goodsphoto'),
        ),
    ]
