# Generated by Django 5.1.7 on 2025-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_goodsphoto_transport_delay_estimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='time_estimation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
