# Generated by Django 5.2 on 2025-05-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='goods_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_truck', models.CharField(default='ok', max_length=100)),
                ('status_truck_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status_goods', models.CharField(default='ok', max_length=100)),
                ('truck_combination', models.CharField(max_length=100)),
                ('status_coupling', models.CharField(default='ok', max_length=100)),
                ('trailer_type', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(max_length=100)),
                ('status_trailer_wagon', models.CharField(default='ok', max_length=100)),
                ('status_trailer_wagon_description', models.TextField(blank=True, null=True)),
                ('status_loaded_truck', models.CharField(default='ok', max_length=100)),
                ('detraction', models.CharField(max_length=100)),
                ('status_transport', models.CharField(default='not started', max_length=100)),
                ('delay_estimation', models.DurationField(blank=True, max_length=100, null=True)),
                ('time_estimation', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('goods_type', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='base.company')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_transports', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_transports', to=settings.AUTH_USER_MODEL)),
                ('goods_photos', models.ManyToManyField(blank=True, to='transports.goodsphoto')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='vehicles.trailer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='vehicles.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.ManyToManyField(to='transports.point')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transports.transport')),
            ],
        ),
        migrations.CreateModel(
            name='CMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expeditor_nume', models.CharField(max_length=255)),
                ('expeditor_adresa', models.CharField(max_length=255)),
                ('expeditor_tara', models.CharField(max_length=100)),
                ('destinatar_nume', models.CharField(max_length=255)),
                ('destinatar_adresa', models.CharField(max_length=255)),
                ('destinatar_tara', models.CharField(max_length=100)),
                ('loc_livrare', models.CharField(max_length=255)),
                ('loc_incarcare', models.CharField(max_length=255)),
                ('data_incarcare', models.DateField()),
                ('marci_numere', models.CharField(max_length=255)),
                ('numar_colete', models.IntegerField()),
                ('mod_ambalare', models.CharField(max_length=255)),
                ('natura_marfii', models.CharField(max_length=255)),
                ('nr_static', models.CharField(max_length=100)),
                ('greutate_bruta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cubaj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructiuni_expeditor', models.TextField(blank=True, null=True)),
                ('conventii_speciale', models.TextField(blank=True, null=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_dispatcher', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_driver', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmrs', to='transports.transport')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(upload_to='transport_documents/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transports.transport')),
            ],
        ),
    ]
