# Generated by Django 5.2 on 2025-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='origin_city',
            field=models.CharField(max_length=100),
        ),
    ]
