# Generated by Django 5.2 on 2025-05-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmr',
            name='UIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='cubaj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='data_incarcare',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='greutate_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='marci_numere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='mod_ambalare',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='natura_marfii',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='nr_static',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='numar_colete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
