# Generated by Django 5.2 on 2025-04-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='base.company'),
        ),
        migrations.AddField(
            model_name='transport',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
