# Generated by Django 5.2 on 2025-05-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_cmr_uit_alter_cmr_cubaj_alter_cmr_data_incarcare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmr',
            name='loc_incarcare',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmr',
            name='loc_livrare',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
