# Generated by Django 5.2 on 2025-04-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_transport_company_transport_destination_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='delay_estimation',
            field=models.DurationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='time_estimation',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
