# Generated by Django 5.2 on 2025-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_cmr_loc_incarcare_alter_cmr_loc_livrare'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmr',
            name='data_emitere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='incheiat_la',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cmr',
            name='numar_cmr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='prescriptii_francare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='rambursare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='rezerve_observatii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='semnatura_destinatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='semnatura_expeditor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='semnatura_transportator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='transportator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmr',
            name='transportatori_succesivi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
