# Generated by Django 5.2 on 2025-05-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_cmr_data_emitere_cmr_incheiat_la_cmr_numar_cmr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmr',
            name='de_plata',
            field=models.JSONField(default=dict),
        ),
    ]
