# Generated by Django 5.2 on 2025-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0005_cmr_de_plata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
