# Generated by Django 5.2 on 2025-05-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0007_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='detraction',
        ),
    ]
