# Generated by Django 5.2 on 2025-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0008_remove_transport_detraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='UIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
