# Generated by Django 5.2 on 2025-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0009_transport_uit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.CharField(default='neatribuit', max_length=100),
        ),
    ]
